# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'JLConsoleLogExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'JLConsoleLog', :path =>'../'
  # Pods for JLConsoleLogExample

  target 'JLConsoleLogExampleTests' do
    inherit! :search_paths
    pod 'FBSnapshotTestCase'
    # Pods for testing
  end
#
#  target 'JLConsoleLogExampleUITests' do
#    # Pods for testing
#  end

end
